### PR TITLE
chore(renovate): disable graphcool PRs

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Comment by rarkins** [comment]
Beware though that this repository uses a `yarn.lock` so depending on how developers run `yarn`, they may still get "old" versions of graphcool when installing.

**Comment by marktani** [comment]
how exactly does this work?
does it prevent incoming PRs [like this](https://github.com/graphql-boilerplates/node-graphql-server/pull/133)? 🙂 

Note that `v1.4.0` is an older version, so I'd like to prevent similar PRs for now.

**Comment by rarkins** [comment]
@marktani I have updated this PR to instead disable `graphcool` updates altogether, if that's what you'd prefer

**Comment by rarkins** [comment]
Please merge squash this PR so that the PR title is used rather than the individual commits.

**Comment by marktani** [comment]
thanks @rarkins, that's super helpful! at least for now this is the preferred option 🙂

**Pull request merged**
